USE [BDCasaColomboDeposito]
GO

/****** Objeto: Table [dbo].[DEPOSITO] Data do Script: 03/05/2024 09:18:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DEPOSITO] (
    [ID]           INT           IDENTITY (1, 1) NOT NULL,
    [NOMEDEPOSITO] NVARCHAR (30) NOT NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_DEPOSITO_NOMEDEPOSITO]
    ON [dbo].[DEPOSITO]([NOMEDEPOSITO] ASC);


GO
ALTER TABLE [dbo].[DEPOSITO]
    ADD CONSTRAINT [PK_DEPOSITO] PRIMARY KEY CLUSTERED ([ID] ASC);


